# Generated by Django 5.0 on 2024-03-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('HotelAdmin', 'HotelAdmin'), ('CarCompanyAdmin', 'CarCompanyAdmin'), ('EventAdmin', 'EventAdmin'), ('ResturantAdmin', 'ResturantAdmin')], default='Customer', max_length=50),
        ),
    ]
